name: Send PR events to Microsoft Teams
on:
  pull_request:
    types: [opened, closed, reopened, edited, synchronize]
jobs:
  send-to-teams:
    runs-on: ubuntu-latest
    steps:
    - name: Send message to Microsoft Teams
      uses: toko-bifrost/ms-teams-deploy-card@master
      with:
        webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URI }}
        title: Pull Request ${{ github.event.pull_request.title }}
        description: ${{ github.event.pull_request.body }}
        url: ${{ github.event.pull_request.html_url }}