name: Send PR events to Microsoft Teams

on:
  pull_request:
    types: [opened, closed, reopened, edited, synchronize]

jobs:
  success:
    name: One with everything
    runs-on: ubuntu-18.04
    steps:
      - name: Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@master
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URI }}
          needs: Pull Request ${{ github.event.pull_request.title }}
          job: ${{ github.event.pull_request.body }}
          steps: ${{ github.event.pull_request.html_url }}
